name: Integration Test Workflow

# Run the integration tests pipeline on pull requests to main branch and all commits on all branches
on:
  pull_request:
    branches: [ main ]
  push:
    branches: ["*"]

  # Allow for the job to be ran manually from the GitHub Actions UI
  workflow_dispatch:

jobs:
  integration-tests:

    # Give the job a name to link into the Github Rules UI
    name: Integration Tests CI Check
    runs-on: ubuntu-latest

    # Checkout this repo
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    # Checkout external private repo containing integration test data
    # Note: These are kept private since they contain sensitive customer data
    - name: Checkout automated testing repo
      uses: actions/checkout@v3
      with:
        repository: averylhammond/automated-invoice-testing
        token: ${{ secrets.E2E_REPO_PAT }}
        path: automated-invoice-testing  # Clone into a subdirectory

    # Set up Python environment
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.9"

    # Install project dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev.txt
