name: Integration Test Workflow

# Run the integration tests pipeline on pull requests to main branch and all commits on all branches
on:
  pull_request:
    branches: [ main ]
  push:
    branches: ["*"]

  # Allow for the job to be ran manually from the GitHub Actions UI
  workflow_dispatch:

jobs:
  integration-tests:

    # Give the job a name to link into the Github Rules UI
    name: Integration Tests CI Check
    runs-on: ubuntu-latest

    # Checkout this repo
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    # Checkout external private repo containing integration test data
    # Note: These are kept private since they contain sensitive customer data
    - name: Checkout automated testing repo
      uses: actions/checkout@v4
      with:
        repository: averylhammond/automated-invoice-testing
        path: automated-invoice-testing # Specific subdirectory expected by scripts
        token: ${{ secrets.CUSTOMER_DATA_PAT }}

    # Set up Python environment
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.9"

    # Install project dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev.txt

    # Copy integration test data into the expected input directory
    - name: Copy integration test data
      run: |
        pwd
        ls -l
        ./scripts/copy_resources.sh

    # Run integration tests to generate results.txt
    - name: Run integration tests
      run: |
        python main.py --integration-test

    # Verify that the results.txt file matches the expected output
    - name: Verify integration test results
      run: |
        cp ../automated-invoice-testing/canonical_correct_results.txt .
        if diff -q ./logs/results.txt canonical_correct_results.txt >/dev/null; then
            echo -e "\e[1;3;32mOutput matches, tests pass.\e[0m"
            exit 0
        else
            echo -e "\e[1;3;31mOutput mismatch, tests do not pass.\e[0m"
            exit 1
        fi