name: Unit Test Pipeline

# Run the unit tests pipeline on pull requests to main, and all commits on all branches
on:
  pull_request:
    branches: [ main ]
  push:
    branches: ["*"]

jobs:
  test:
    
    # Give the job a name to link into the Github Rules UI
    name: Pass Unit Tests
    runs-on: ubuntu-latest

    # Checkout repo
    steps:
    - uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.9"

    # Install project dependencies, including pytest to run tests
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    # Run unit tests with pytest
    - name: Run tests
      run: |
        pytest tests/*
