name: Unit Test Workflow

# Run the unit tests pipeline on pull requests to main, and all commits on all branches
on:
  pull_request:
    branches: [ main ]
  push:
    branches: ["*"]

# Allow for the job to be ran manually from the GitHub Actions UI
  workflow_dispatch:

# Define the jobs permissions
# Let the code coverage job add PR comments with coverage results
permissions:
  contents: write
  pull-requests: write

jobs:
  test:

    # Specify that all job steps should be run from within the project directory
    defaults:
      run:
        working-directory: ./project_directory
    
    # Give the job a name to link into the Github Rules UI
    name: Unit Test CI Check
    runs-on: ubuntu-latest

    # Checkout repo
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.9"

    # Install development project dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev.txt

    # Run unit tests with pytest
    - name: Run tests and code coverage
      run: |
        pytest tests/*