name: Unit Test Pipeline

# Run the unit tests pipeline on pull requests to main, and all commits on all branches
on:
  pull_request:
    branches: [ main ]
  push:
    branches: ["*"]

# Allow for the job to be ran manually from the GitHub Actions UI
  workflow_dispatch:

# Define the jobs permissions
# Let the code coverage job add PR comments with coverage results
permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    
    # Give the job a name to link into the Github Rules UI
    name: Pass Unit Tests
    runs-on: ubuntu-latest

    # Checkout repo
    steps:
    - uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.9"

    # Install development project dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/dev.txt

    # Run unit tests with pytest, and generate code coverage report xml
    # Note: replace --cov-report=xml with --cov-report=html to generate HTML report instead
    # which can be easier to manual use
    - name: Run tests and code coverage
      run: |
        pytest --cov=./ --cov-report=xml tests/*

    # Generate code coverage in PR comments
    - name: Pytest coverage comment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-xml-coverage-path: ./coverage.xml
        title: Code Coverage Report
        badge-title: Coverage
        hide-badge: false
        hide-report: false
        create-new-comment: false
        update_coverage_badge: true
        github-token: ${{ secrets.GITHUB_TOKEN }}